version: "3.8"

services:
  api-flutter:
    build: ./
    container_name: api-flutter
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0.30
    container_name: mysql_db_flutter
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DBuser
    ports:
      - "3307:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
